mode: 'usage'
source: './src/source/Internal'
ignore:
  - Container
  - Theme
  - Transition
filePattern: '*.php'
formatter: 'PhpDA\Writer\Strategy\PackageLevel1DependencyReporter'
target: './PACKAGE_LVL_1.svg'
visitor:
  - PhpDA\Parser\Visitor\TagCollector
  - PhpDA\Parser\Visitor\SuperglobalCollector
visitorOptions:
  PhpDA\Parser\Visitor\Required\DeclaredNamespaceCollector: {minDepth: 4, sliceLength: 5}
  PhpDA\Parser\Visitor\Required\MetaNamespaceCollector: {minDepth: 4, sliceLength: 5}
  PhpDA\Parser\Visitor\Required\UsedNamespaceCollector: {minDepth: 4, sliceLength: 5}
  PhpDA\Parser\Visitor\TagCollector: {minDepth: 4, sliceLength: 5}
